version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=shuffle_db
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8083:8083'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shuffle_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234

volumes:
  pgdata:
