version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  spring-app:
    image: 'your-spring-boot-image'
    ports:
      - '8081:8081'
    depends_on:
      - postgres
