version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=shuffle_db'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  spring-app:
    image: 'shuffler_web'
    ports:
      - '8081:8081'
    depends_on:
      - postgres
